// Generated by phase4_build_config.py. This file is excluded from its own identity.
package iq_build_config;
 localparam integer SAMPLE_RATE_HZ = 125000000;
 localparam integer TIMESTAMP_CLOCK_HZ = 125000000;
 localparam integer FFT_CLOCK_HZ = 125000000;
 localparam integer HARDWARE_VERSION = 65541;
 localparam integer CAPABILITIES = 31;
 localparam integer RECORD_FORMAT_VERSION = 1;
 localparam integer SCAN_LANES = 8;
 localparam integer FFT_LENGTH = 16384;
 localparam integer FFT_LOG2 = 14;
 localparam integer REPLAY_BANK_SAMPLES = 32768;
 localparam integer SNAPSHOT_POINTS = 1024;
 localparam integer SNAPSHOT_GROUP = 16;
 localparam integer INPUT_FIFO_DEPTH = 4096;
 localparam integer FREQUENCY_RECORDS = 128;
 localparam integer FREQUENCY_RECORDS_LOG2 = 7;
 localparam integer SPECTRUM_LUTRAM_BANK = 1;
 localparam integer FFT_SCALE_SHIFT = 15;
 localparam integer FFT_CONFIG_WIDTH = 16;
 localparam integer FFT_CONFIG_WORD = 21847;
 localparam logic [127:0] BUILD_ID = 128'h803909d3e072d6116e282fcea9d99b06;
endpackage
