// Generated by phase4_build_config.py. This file is excluded from its own identity.
package iq_build_config;
 localparam integer SAMPLE_RATE_HZ = 125000000;
 localparam integer TIMESTAMP_CLOCK_HZ = 125000000;
 localparam integer FFT_CLOCK_HZ = 125000000;
 localparam integer HARDWARE_VERSION = 65538;
 localparam integer CAPABILITIES = 3;
 localparam integer RECORD_FORMAT_VERSION = 1;
 localparam integer SCAN_LANES = 8;
 localparam logic [127:0] BUILD_ID = 128'ha7754c225c36a9f7e69d1d024250d0c2;
endpackage
