"""Derive an auditable 128-bit hardware build identity before any build stage."""
import argparse
import hashlib
import json
from pathlib import Path
ROOT=Path(__file__).resolve().parents[1]
GENERATED=ROOT/'rtl/iq_build_config.sv'
CLOCK_ATTRIBUTES=ROOT/'rtl/iq_clock_attributes.svh'
VALID_CLOCK_PROFILES={(100000000,125000000),(125000000,125000000),(125000000,150000000)}
def digest(p):return hashlib.sha256(p.read_bytes()).hexdigest()
def main():
    parser=argparse.ArgumentParser();parser.add_argument('--check',action='store_true');a=parser.parse_args()
    profile=json.loads((ROOT/'config/build_profile.json').read_text())
    n=profile.setdefault('fft_length',8192)
    if n not in (8192,16384,32768):raise ValueError('Unsupported FFT length')
    logn=n.bit_length()-1
    profile.setdefault('replay_bank_samples',32768)
    profile.setdefault('snapshot_points',1024)
    profile.setdefault('input_fifo_depth',4096)
    profile.setdefault('frequency_records',256 if n==8192 else 128)
    profile.setdefault('spectrum_lutram_bank',0)
    profile.setdefault('fft_bram_stages',6)
    if profile['replay_bank_samples']!=32768 or profile['snapshot_points']!=1024 or profile['scan_lanes']!=8:
        raise ValueError('This release retains 32768-pair banks, 1024 snapshots and eight scan lanes')
    if profile['input_fifo_depth']!=4096:raise ValueError('Input FIFO capacity is retained')
    if profile['frequency_records'] not in (128,256):raise ValueError('Invalid frequency ring capacity')
    if profile['spectrum_lutram_bank'] not in (0,1):raise ValueError('Invalid spectrum storage profile')
    scaling=[3]+[2]*(logn//2-1)+([1] if logn%2 else [])
    config_word=1 | (sum(v<<(2*i) for i,v in enumerate(scaling))<<1)
    config_width=((1+2*len(scaling)+7)//8)*8
    if profile['sample_rate_hz']!=profile['timestamp_clock_hz']:raise ValueError('This architecture shares source and timestamp domains')
    clock_profile=(profile['sample_rate_hz'],profile['fft_clock_hz'])
    if clock_profile not in VALID_CLOCK_PROFILES:
        raise ValueError(f'Unsupported physical clock profile: {clock_profile}')
    files=list((ROOT/'rtl').glob('*.sv'))+list((ROOT/'constraints').glob('*'))+list((ROOT/'vendor/boards').rglob('*.xml'))
    files += [ROOT/'config/build_profile.json',ROOT/'data/hann_u18_f17.mem',ROOT/'data/hann_quarter_u18_f17.mem',Path(__file__)]
    files += [ROOT/'scripts'/n for n in ('create_fft.tcl','build_board.tcl','rebuild_board.tcl','finish_board.tcl','phase3_replication_hook.tcl')]
    generated_files={GENERATED,CLOCK_ATTRIBUTES}
    inputs={p.relative_to(ROOT).as_posix():digest(p) for p in sorted(files) if p.is_file() and p not in generated_files}
    full=hashlib.sha256(json.dumps(inputs,sort_keys=True,separators=(',',':')).encode()).hexdigest()
    lines=['// Generated by phase4_build_config.py. This file is excluded from its own identity.','package iq_build_config;']
    for k in ('sample_rate_hz','timestamp_clock_hz','fft_clock_hz','hardware_version','capabilities','record_format_version','scan_lanes'):
        lines.append(f' localparam integer {k.upper()} = {profile[k]};')
    constants=dict(FFT_LENGTH=n,FFT_LOG2=logn,REPLAY_BANK_SAMPLES=profile['replay_bank_samples'],
        SNAPSHOT_POINTS=profile['snapshot_points'],SNAPSHOT_GROUP=n//profile['snapshot_points'],
        INPUT_FIFO_DEPTH=profile['input_fifo_depth'],FREQUENCY_RECORDS=profile['frequency_records'],
        FREQUENCY_RECORDS_LOG2=profile['frequency_records'].bit_length()-1,
        SPECTRUM_LUTRAM_BANK=profile['spectrum_lutram_bank'],FFT_SCALE_SHIFT=sum(scaling),
        FFT_CONFIG_WIDTH=config_width,FFT_CONFIG_WORD=config_word)
    lines += [f' localparam integer {k} = {v};' for k,v in constants.items()]
    lines += [f" localparam logic [127:0] BUILD_ID = 128'h{full[:32]};",'endpackage','']
    content='\n'.join(lines)
    clock_attributes=(
        '// Generated by phase4_build_config.py.\n'
        f'`define IQ_AXI_CLOCK_PARAMETER "ASSOCIATED_BUSIF S_AXI:S_AXIS_IQ, ASSOCIATED_RESET s_axi_aresetn, FREQ_HZ {profile["sample_rate_hz"]}"\n'
        f'`define IQ_FFT_CLOCK_PARAMETER "FREQ_HZ {profile["fft_clock_hz"]}"\n')
    clocks=f"set sample_rate_mhz {profile['sample_rate_hz']/1e6:g}\nset fft_clock_mhz {profile['fft_clock_hz']/1e6:g}\n"
    fft_tcl=f"set fft_length {n}\nset fft_bram_stages {profile['fft_bram_stages']}\n"
    out=ROOT/'build/config';report=dict(profile=profile,inputs=inputs,full_input_sha256=full,build_id=full[:32],
        identity_scope='Source/config identity, not bitstream hash or authentication')
    if a.check:
        assert GENERATED.read_text()==content,'Generated build identity is stale'
        assert CLOCK_ATTRIBUTES.read_text()==clock_attributes,'Generated interface clock metadata changed'
        assert (out/'generated_clocks.tcl').read_text()==clocks,'Generated clocks changed'
        assert (out/'generated_fft.tcl').read_text()==fft_tcl,'Generated FFT configuration changed'
        assert json.loads((out/'build_identity.json').read_text())==report,'Identity manifest changed'
    else:
        out.mkdir(parents=True,exist_ok=True)
        # Vivado tracks source mtimes as well as contents. Do not invalidate
        # an in-flight OOC synthesis when an independent Sim checks identity.
        for path,value in ((GENERATED,content),(CLOCK_ATTRIBUTES,clock_attributes),(out/'generated_clocks.tcl',clocks),
                           (out/'generated_fft.tcl',fft_tcl),(out/'build_identity.json',json.dumps(report,indent=2)+'\n')):
            if not path.exists() or path.read_text()!=value:path.write_text(value)
    print('BUILD_IDENTITY_PASS',full[:32])
if __name__=='__main__':main()
