"""Derive an auditable 128-bit hardware build identity before any build stage."""
import argparse
import hashlib
import json
from pathlib import Path
ROOT=Path(__file__).resolve().parents[1]
GENERATED=ROOT/'rtl/iq_build_config.sv'
CLOCK_ATTRIBUTES=ROOT/'rtl/iq_clock_attributes.svh'
VALID_CLOCK_PROFILES={(100000000,125000000),(125000000,125000000),(125000000,150000000)}
def digest(p):return hashlib.sha256(p.read_bytes()).hexdigest()
def main():
    parser=argparse.ArgumentParser();parser.add_argument('--check',action='store_true');a=parser.parse_args()
    profile=json.loads((ROOT/'config/build_profile.json').read_text())
    if profile['sample_rate_hz']!=profile['timestamp_clock_hz']:raise ValueError('This architecture shares source and timestamp domains')
    clock_profile=(profile['sample_rate_hz'],profile['fft_clock_hz'])
    if clock_profile not in VALID_CLOCK_PROFILES:
        raise ValueError(f'Unsupported physical clock profile: {clock_profile}')
    files=list((ROOT/'rtl').glob('*.sv'))+list((ROOT/'constraints').glob('*'))+list((ROOT/'vendor/boards').rglob('*.xml'))
    files += [ROOT/'config/build_profile.json',ROOT/'data/hann_u18_f17.mem',Path(__file__)]
    files += [ROOT/'scripts'/n for n in ('create_fft.tcl','build_board.tcl','rebuild_board.tcl','finish_board.tcl','phase3_replication_hook.tcl')]
    generated_files={GENERATED,CLOCK_ATTRIBUTES}
    inputs={p.relative_to(ROOT).as_posix():digest(p) for p in sorted(files) if p.is_file() and p not in generated_files}
    full=hashlib.sha256(json.dumps(inputs,sort_keys=True,separators=(',',':')).encode()).hexdigest()
    lines=['// Generated by phase4_build_config.py. This file is excluded from its own identity.','package iq_build_config;']
    for k in ('sample_rate_hz','timestamp_clock_hz','fft_clock_hz','hardware_version','capabilities','record_format_version','scan_lanes'):
        lines.append(f' localparam integer {k.upper()} = {profile[k]};')
    lines += [f" localparam logic [127:0] BUILD_ID = 128'h{full[:32]};",'endpackage','']
    content='\n'.join(lines)
    clock_attributes=(
        '// Generated by phase4_build_config.py.\n'
        f'`define IQ_AXI_CLOCK_PARAMETER "ASSOCIATED_BUSIF S_AXI:S_AXIS_IQ, ASSOCIATED_RESET s_axi_aresetn, FREQ_HZ {profile["sample_rate_hz"]}"\n'
        f'`define IQ_FFT_CLOCK_PARAMETER "FREQ_HZ {profile["fft_clock_hz"]}"\n')
    clocks=f"set sample_rate_mhz {profile['sample_rate_hz']/1e6:g}\nset fft_clock_mhz {profile['fft_clock_hz']/1e6:g}\n"
    out=ROOT/'build/config';report=dict(profile=profile,inputs=inputs,full_input_sha256=full,build_id=full[:32],
        identity_scope='Source/config identity, not bitstream hash or authentication')
    if a.check:
        assert GENERATED.read_text()==content,'Generated build identity is stale'
        assert CLOCK_ATTRIBUTES.read_text()==clock_attributes,'Generated interface clock metadata changed'
        assert (out/'generated_clocks.tcl').read_text()==clocks,'Generated clocks changed'
        assert json.loads((out/'build_identity.json').read_text())==report,'Identity manifest changed'
    else:
        out.mkdir(parents=True,exist_ok=True)
        # Vivado tracks source mtimes as well as contents. Do not invalidate
        # an in-flight OOC synthesis when an independent Sim checks identity.
        for path,value in ((GENERATED,content),(CLOCK_ATTRIBUTES,clock_attributes),(out/'generated_clocks.tcl',clocks),
                           (out/'build_identity.json',json.dumps(report,indent=2)+'\n')):
            if not path.exists() or path.read_text()!=value:path.write_text(value)
    print('BUILD_IDENTITY_PASS',full[:32])
if __name__=='__main__':main()
